### ISSUE TITLE
Cannot use this Vite plugin with "eslint-plugin-vue" and "vue-eslint-parser"

### ISSUE THREAD

**Issue by tianxiang24** [ota-meshi/vite-plugin-eslint4b#11]
Hello!

## Description
I tried to use this plugin with `eslint-plugin-vue` and `vue-eslint-parser` to lint my vue components in browser like [eslint-plugin-vue-demo](https://github.com/ota-meshi/eslint-plugin-vue-demo/tree/main).
But I get  the following error:
```
✘ [ERROR] Could not read from file: /Users/xxxx/vite-plugin-eslint4b/tests/vue-app/virtual:eslint4b_eslint

    node_modules/.pnpm/eslint-plugin-vue@9.14.0/node_modules/eslint-plugin-vue/lib/utils/index.js:80:25:
      80 │   const eslint = require('eslint')
```

## Reproduction

https://github.com/randomVariable2000/vite-plugin-eslint4b/commit/ea3e56ec968bf814d278cfbe71fd603aae078ede

**Comment by ota-meshi** [comment]
`eslint-plugin-vue` has a lot of code that only works with CJS, so it's very incompatible with Vite.

`eslint-plugin-vue-demo` used Vue CLI and webpack.
`eslint-plugin-vue` documentation site uses a special vite plugin. I'm glad if you can use it as a reference.
https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/.vitepress/vite-plugin.ts

**Comment by randomVariable2000** [comment]
Thanks!
